// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pampeliska.Core.Data;

#nullable disable

namespace Pampeliska.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pampeliska.Core.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<bool>("CardToHolder")
                        .HasColumnType("boolean")
                        .HasColumnName("card_to_holder");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<int?>("FundingAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("funding_account_id");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<bool>("IncludeInDisposable")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_disposable");

                    b.Property<bool>("IncludeInNetWorth")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_net_worth");

                    b.Property<string>("InstitutionKey")
                        .IsRequired()
                        .HasColumnType("character varying(32)")
                        .HasColumnName("institution_key");

                    b.Property<decimal?>("InterestRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("interest_rate");

                    b.Property<int?>("InvestmentKind")
                        .HasColumnType("integer")
                        .HasColumnName("investment_kind");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<decimal?>("LowBalanceLimit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("low_balance_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("opening_balance");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date")
                        .HasColumnName("opening_date");

                    b.Property<decimal?>("OpeningDeposits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("opening_deposits");

                    b.Property<int?>("OwnerMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_member_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("ValueTracking")
                        .HasColumnType("integer")
                        .HasColumnName("value_tracking");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("InstitutionKey")
                        .HasDatabaseName("ix_accounts_institution_key");

                    b.HasIndex("OwnerMemberId")
                        .HasDatabaseName("ix_accounts_owner_member_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.AccountCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Benefit")
                        .HasColumnType("text")
                        .HasColumnName("benefit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_account_conditions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_conditions_account_id");

                    b.ToTable("account_conditions", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.AccountShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<decimal>("Percent")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("percent");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.HasKey("Id")
                        .HasName("pk_account_shares");

                    b.HasIndex("AccountId", "ValidFrom")
                        .HasDatabaseName("ix_account_shares_account_id_valid_from");

                    b.ToTable("account_shares", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.BackupRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_backup_runs");

                    b.ToTable("backup_runs", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BudgetAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("budget_amount");

                    b.Property<int>("BudgetPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("budget_period");

                    b.Property<bool>("CarryOver")
                        .HasColumnType("boolean")
                        .HasColumnName("carry_over");

                    b.Property<string>("ColorToken")
                        .HasColumnType("text")
                        .HasColumnName("color_token");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fixed");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Need")
                        .HasColumnType("integer")
                        .HasColumnName("need");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate");

                    b.HasKey("Id")
                        .HasName("pk_exchange_rates");

                    b.HasIndex("Date", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_exchange_rates_date_currency");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_currency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CategorizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("categorized_at");

                    b.Property<string>("ClientName")
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_member_id");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OAuthClientId")
                        .HasColumnType("text")
                        .HasColumnName("o_auth_client_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("SuspectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("suspected_count");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_import_batches_created_at");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Institution", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("Abbrev")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbrev");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key")
                        .HasName("pk_institutions");

                    b.ToTable("institutions", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.InvestmentTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("LinkedTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_transaction_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.HasKey("Id")
                        .HasName("pk_investment_trades");

                    b.HasIndex("AccountId", "Date")
                        .HasDatabaseName("ix_investment_trades_account_id_date");

                    b.ToTable("investment_trades", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.InvestmentValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_investment_values");

                    b.HasIndex("AccountId", "Date")
                        .HasDatabaseName("ix_investment_values_account_id_date");

                    b.ToTable("investment_values", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessScope")
                        .HasColumnType("integer")
                        .HasColumnName("access_scope");

                    b.Property<string>("ColorToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_members_email");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.MemberBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<bool>("CarryOver")
                        .HasColumnType("boolean")
                        .HasColumnName("carry_over");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.HasKey("Id")
                        .HasName("pk_member_budgets");

                    b.HasIndex("CategoryId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_budgets_category_id_member_id");

                    b.ToTable("member_budgets", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.MemberPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_member_preferences");

                    b.HasIndex("MemberId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_member_preferences_member_id_key");

                    b.ToTable("member_preferences", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int?>("RecurringPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("recurring_payment_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_notifications_key");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.OAuthAuthorizationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_challenge");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("GrantId")
                        .HasColumnType("integer")
                        .HasColumnName("grant_id");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redirect_uri");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_oauth_authorization_codes");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_authorization_codes_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_oauth_authorization_codes_expires_at");

                    b.ToTable("oauth_authorization_codes", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.OAuthClient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastAuthorizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_authorized_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("RedirectUris")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("SecretHash")
                        .HasColumnType("text")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_oauth_clients");

                    b.ToTable("oauth_clients", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.OAuthGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_oauth_grants");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_oauth_grants_client_id");

                    b.ToTable("oauth_grants", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("GrantId")
                        .HasColumnType("integer")
                        .HasColumnName("grant_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_oauth_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_oauth_tokens_expires_at");

                    b.HasIndex("GrantId")
                        .HasDatabaseName("ix_oauth_tokens_grant_id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_tokens_hash");

                    b.ToTable("oauth_tokens", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.RecurringPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly?>("AmountAlertDismissedFor")
                        .HasColumnType("date")
                        .HasColumnName("amount_alert_dismissed_for");

                    b.Property<int>("AmountKind")
                        .HasColumnType("integer")
                        .HasColumnName("amount_kind");

                    b.Property<DateOnly>("AnchorDate")
                        .HasColumnType("date")
                        .HasColumnName("anchor_date");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndedAt")
                        .HasColumnType("date")
                        .HasColumnName("ended_at");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_transfer");

                    b.Property<bool>("MarkedToCancel")
                        .HasColumnType("boolean")
                        .HasColumnName("marked_to_cancel");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("ToleranceDays")
                        .HasColumnType("integer")
                        .HasColumnName("tolerance_days");

                    b.Property<int>("VariancePct")
                        .HasColumnType("integer")
                        .HasColumnName("variance_pct");

                    b.HasKey("Id")
                        .HasName("pk_recurring_payments");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_recurring_payments_account_id");

                    b.ToTable("recurring_payments", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.RecurringSkip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("RecurringPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("recurring_payment_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_skips");

                    b.HasIndex("RecurringPaymentId", "DueDate")
                        .IsUnique()
                        .HasDatabaseName("ix_recurring_skips_recurring_payment_id_due_date");

                    b.ToTable("recurring_skips", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("ExcludeFromStats")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_from_stats");

                    b.Property<int>("Logic")
                        .HasColumnType("integer")
                        .HasColumnName("logic");

                    b.Property<bool>("MarkRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("mark_recurring");

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int?>("NeedOverride")
                        .HasColumnType("integer")
                        .HasColumnName("need_override");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_rules_category_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_rules_priority");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.RuleCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Field")
                        .HasColumnType("integer")
                        .HasColumnName("field");

                    b.Property<int>("Op")
                        .HasColumnType("integer")
                        .HasColumnName("op");

                    b.Property<int>("RuleId")
                        .HasColumnType("integer")
                        .HasColumnName("rule_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_rule_conditions");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_rule_conditions_rule_id");

                    b.ToTable("rule_conditions", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.RuleSuggestionDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.HasKey("Id")
                        .HasName("pk_rule_suggestion_dismissals");

                    b.ToTable("rule_suggestion_dismissals", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.SkippedDuplicate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("counterparty");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("ExistingTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("existing_transaction_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("Id")
                        .HasName("pk_skipped_duplicates");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_skipped_duplicates_batch_id");

                    b.ToTable("skipped_duplicates", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("AiAlternatives")
                        .HasColumnType("text")
                        .HasColumnName("ai_alternatives");

                    b.Property<int?>("AiConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("AiReason")
                        .HasColumnType("text")
                        .HasColumnName("ai_reason");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountCzk")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_czk");

                    b.Property<int?>("AppliedRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("applied_rule_id");

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<int?>("CardHolderMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("card_holder_member_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("CategorySource")
                        .HasColumnType("integer")
                        .HasColumnName("category_source");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("counterparty");

                    b.Property<string>("CounterpartyAccount")
                        .HasColumnType("text")
                        .HasColumnName("counterparty_account");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<bool>("ExcludeFromStats")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_from_stats");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fx_rate");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Mcc")
                        .HasColumnType("text")
                        .HasColumnName("mcc");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("NeedOverride")
                        .HasColumnType("integer")
                        .HasColumnName("need_override");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<int?>("RecurringPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("recurring_payment_id");

                    b.Property<int?>("RefundOfId")
                        .HasColumnType("integer")
                        .HasColumnName("refund_of_id");

                    b.Property<bool>("SharesOverridden")
                        .HasColumnType("boolean")
                        .HasColumnName("shares_overridden");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SuspectedDuplicateOfId")
                        .HasColumnType("integer")
                        .HasColumnName("suspected_duplicate_of_id");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<int?>("TransferPairId")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_pair_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_transactions_batch_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_transactions_date");

                    b.HasIndex("DedupKey")
                        .HasDatabaseName("ix_transactions_dedup_key");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_transactions_external_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_transactions_status");

                    b.HasIndex("AccountId", "Date")
                        .HasDatabaseName("ix_transactions_account_id_date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.TransactionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction_events");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_transaction_events_transaction_id");

                    b.ToTable("transaction_events", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.TransactionShare", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<decimal>("Percent")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("percent");

                    b.HasKey("TransactionId", "MemberId")
                        .HasName("pk_transaction_shares");

                    b.ToTable("transaction_shares", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.TransactionSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("NeedOverride")
                        .HasColumnType("integer")
                        .HasColumnName("need_override");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction_splits");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transaction_splits_category_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_transaction_splits_transaction_id");

                    b.ToTable("transaction_splits", (string)null);
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Account", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_institutions_institution_key");

                    b.HasOne("Pampeliska.Core.Domain.Member", "OwnerMember")
                        .WithMany()
                        .HasForeignKey("OwnerMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_members_owner_member_id");

                    b.Navigation("Institution");

                    b.Navigation("OwnerMember");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.AccountCondition", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Account", null)
                        .WithMany("Conditions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_conditions_accounts_account_id");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.AccountShare", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Account", null)
                        .WithMany("Shares")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_shares_accounts_account_id");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Category", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Household", b =>
                {
                    b.OwnsOne("Pampeliska.Core.Domain.HouseholdSettings", "Settings", b1 =>
                        {
                            b1.Property<int>("HouseholdId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("AiAutoConfirmThreshold")
                                .HasColumnType("integer")
                                .HasColumnName("settings_ai_auto_confirm_threshold");

                            b1.Property<bool>("ConfirmedOnlyDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("settings_confirmed_only_default");

                            b1.Property<int>("DedupWindowDays")
                                .HasColumnType("integer")
                                .HasColumnName("settings_dedup_window_days");

                            b1.Property<int>("DefaultPeriod")
                                .HasColumnType("integer")
                                .HasColumnName("settings_default_period");

                            b1.Property<int>("FxMode")
                                .HasColumnType("integer")
                                .HasColumnName("settings_fx_mode");

                            b1.Property<bool>("HideAmountsOnStart")
                                .HasColumnType("boolean")
                                .HasColumnName("settings_hide_amounts_on_start");

                            b1.Property<int>("MainChart")
                                .HasColumnType("integer")
                                .HasColumnName("settings_main_chart");

                            b1.Property<string>("NetWorthAltCurrency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("settings_net_worth_alt_currency");

                            b1.Property<bool>("NotifyConditions")
                                .HasColumnType("boolean")
                                .HasColumnName("settings_notify_conditions");

                            b1.Property<bool>("NotifyLowBalance")
                                .HasColumnType("boolean")
                                .HasColumnName("settings_notify_low_balance");

                            b1.Property<bool>("OnboardingDone")
                                .HasColumnType("boolean")
                                .HasColumnName("settings_onboarding_done");

                            b1.Property<bool>("SuggestRules")
                                .HasColumnType("boolean")
                                .HasColumnName("settings_suggest_rules");

                            b1.Property<int>("Theme")
                                .HasColumnType("integer")
                                .HasColumnName("settings_theme");

                            b1.HasKey("HouseholdId");

                            b1.ToTable("households");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdId")
                                .HasConstraintName("fk_households_households_id");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.OAuthGrant", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.OAuthClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_grants_oauth_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.OAuthToken", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.OAuthGrant", "Grant")
                        .WithMany("Tokens")
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_tokens_oauth_grants_grant_id");

                    b.Navigation("Grant");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Rule", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rules_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.RuleCondition", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Rule", null)
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_conditions_rules_rule_id");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.SkippedDuplicate", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.ImportBatch", null)
                        .WithMany("SkippedDuplicates")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skipped_duplicates_import_batches_batch_id");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Transaction", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("Pampeliska.Core.Domain.ImportBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_import_batches_batch_id");

                    b.HasOne("Pampeliska.Core.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.Navigation("Account");

                    b.Navigation("Batch");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.TransactionEvent", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Transaction", null)
                        .WithMany("Events")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_events_transactions_transaction_id");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.TransactionShare", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Transaction", null)
                        .WithMany("Shares")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_shares_transactions_transaction_id");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.TransactionSplit", b =>
                {
                    b.HasOne("Pampeliska.Core.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_splits_categories_category_id");

                    b.HasOne("Pampeliska.Core.Domain.Transaction", null)
                        .WithMany("Splits")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_splits_transactions_transaction_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Account", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.ImportBatch", b =>
                {
                    b.Navigation("SkippedDuplicates");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.OAuthGrant", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Rule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("Pampeliska.Core.Domain.Transaction", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Shares");

                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
